name: flutter_movie
description: flutter application for flutter movie

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #  Core - Data & Domain Deps
  cupertino_icons: ^1.0.0
  injectable: ^1.0.7
  http: ^0.12.1
  get_it: ^5.0.4
  dio: ^3.0.10
  retrofit: ^1.3.4+1
  json_serializable: ^3.5.0
  json_annotation:
  alice: ^0.1.5
  fluro: ^1.7.7
  flutter_bloc: ^6.1.0
  freezed: ^0.12.6
  equatable: ^1.0.0
  async: ^2.4.2
  retry: ^3.0.1
  states_rebuilder: ^3.2.0
  rxdart: ^0.24.1
  google_fonts: ^1.1.1
  device_info: ^1.0.0
  package_info: ^0.4.3+2
  permission_handler: ^5.0.1+1
  connectivity: ^2.0.2
  fluttertoast: ^7.1.6
  flutter_advanced_networkimage: 0.7.0

dependency_overrides:
  analyzer: '0.41.1'

dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator: ^1.4.1+1
  build_runner: ^1.10.1
  injectable_generator: ^1.0.7

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - asset/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Gilroy
      fonts:
        - asset: fonts/Gilroy-Black.otf
        - asset: fonts/Gilroy-BlackItalic.otf
        - asset: fonts/Gilroy-Bold.otf
        - asset: fonts/Gilroy-BoldItalic.otf
        - asset: fonts/Gilroy-Extrabold.otf
        - asset: fonts/Gilroy-Heavy.otf
        - asset: fonts/Gilroy-HeavyItalic.otf
        - asset: fonts/Gilroy-Light.otf
        - asset: fonts/Gilroy-Medium.otf
        - asset: fonts/Gilroy-Regular.otf
        - asset: fonts/Gilroy-SemiBold.otf
        - asset: fonts/Gilroy-Thin.otf
        - asset: fonts/Gilroy-UltraLight.otf
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
